export const naturalHindiTranslations = {
  account_settings: "अकाउंट सेटिंग्स",
  preferences: "पसंद की सेटिंग्स",
  reminder: "रिमाइंडर",
  account_security: "अकाउंट और सुरक्षा",
  linked_account: "लिंक किया हुआ अकाउंट",
  payment_method: "पेमेंट तरीका",
  data_analytics: "डेटा और एनालिटिक्स",
  app_appearance: "ऐप का लुक",
  help_support: "मदद और सपोर्ट",
  logout: "लॉग आउट",
  upgrade_premium: "प्रीमियम लें",
  active_premium: "FlowAI प्रीमियम चालू है",
  try_free: "फ्री में ट्राई करें",
  active: "चालू",
  pro_badge: "प्रो",
  display_units: "यूनिट सेटिंग्स",
  daily_health_goals: "रोज के हेल्थ गोल",
  save_preferences: "सेटिंग्स सेव करें",
  language: "भाषा",
  currency: "करेंसी",
  billing_period: "बिलिंग अवधि",
  cancel_subscription: "सब्सक्रिप्शन बंद करें",
  back_to_free: "सब्सक्रिप्शन बंद हो गया है। अब आप फ्री प्लान पर हैं।",
  success_mfa: "2FA चालू हो गया!",
  success_pref: "सेटिंग्स सेव हो गईं!",
  success_profile: "बदलाव सेव हो गए!",
  cancel: "रद्द करें",
  save: "सेव करें",
  close: "बंद करें",
  nav_home: "होम",
  nav_calendar: "कैलेंडर",
  nav_log: "लॉग",
  nav_ai_coach: "AI कोच",
  nav_account: "अकाउंट",
  nav_community: "कम्युनिटी",
  greet_morning: "गुड मॉर्निंग",
  greet_afternoon: "गुड आफ्टरनून",
  greet_evening: "गुड इवनिंग",
  ask_ai: "AI से पूछें",
  steps_goal: "स्टेप्स का गोल",
  water_goal: "लीटर का गोल",
  sleep_goal: "घंटे का गोल",
  days_remaining: "दिन बाकी",
  days_to_period: "पीरियड आने में दिन",
  day: "दिन",
  how_feeling: "आज आप कैसा महसूस कर रही हैं?",
  more: "और",
  insights: "इनसाइट्स",
  todays_overview: "आज का ओवरव्यू",
  phase_insight: "फेज इनसाइट",
  stat_cycle_length: "साइकिल की लंबाई",
  stat_period_length: "पीरियड की लंबाई",
  stat_next_period: "अगला पीरियड",
  stat_ai_next_period: "AI वाला अगला पीरियड",
  stat_water_today: "आज का पानी",
  unit_days: "दिन",
  phase_period: "पीरियड",
  phase_low_fertility: "कम फर्टाइल",
  phase_fertile: "फर्टाइल",
  phase_ovulation: "ओव्यूलेशन",
  phase_safe: "सेफ",
  phase_very_safe: "बहुत सेफ",
  mood_happy: "खुश",
  mood_calm: "शांत",
  mood_sad: "उदास",
  mood_irritated: "चिड़चिड़ा",
  mood_anxious: "घबराहट",
  mood_energetic: "एनर्जेटिक",
  day_streak: "दिन की स्ट्रीक",
  logs_this_month: "इस महीने के लॉग",
  symptoms_card: "लक्षण लॉग करें",
  track_symptoms: "शरीर और मूड ट्रैक करें",
  log_today: "शुरू करने के लिए आज लॉग करें!",
  on_fire: "बढ़िया चल रहा है!",
  snap_consistency: "बहुत अच्छी consistency!",
  snap_keep_tracking: "ट्रैक करते रहें!",
  insight_title_menstrual: "आज आराम करें और आयरन लें",
  insight_title_follicular: "एनर्जी बढ़ रही है, नया काम शुरू करें!",
  insight_title_ovulation: "आज एनर्जी और creativity पीक पर है!",
  insight_title_luteal: "धीरे चलें, शरीर को आराम चाहिए",
  insight_desc_menstrual: "पालक, दाल और डार्क चॉकलेट खाएं। कैफीन कम रखें। आपका शरीर मेहनत कर रहा है।",
  insight_desc_follicular: "एस्ट्रोजन बढ़ रहा है। वर्कआउट, लोगों से मिलना और गोल पूरे करना अच्छा रहेगा।",
  insight_desc_ovulation: "फर्टिलिटी और creativity high है। जरूरी फैसलों के लिए अच्छा दिन है।",
  insight_desc_luteal: "शरीर comfort चाहता है। नींद, गरम खाना और हल्की movement को priority दें।",
  calendar: "कैलेंडर",
  track_journey: "अपनी cycle journey ट्रैक करें",
  fertile_window: "फर्टाइल विंडो",
  edit_period_dates: "पीरियड की तारीख बदलें",
  no_log_yet: "इस दिन का कोई लॉग नहीं है",
  add_log: "लॉग जोड़ें",
  cycle_legend_normal: "नॉर्मल",
  day_of_cycle: "साइकिल का दिन {{day}}",
  hormonal_health: "आपकी personal hormonal health assistant.",
  welcome_msg: "हाय! मैं FlowAI Coach हूं, आपकी personal hormonal health assistant.\n\nआप अपनी cycle के दिन {{day}} पर हैं, अभी {{phase}} phase चल रहा है। मैं आपके health data के हिसाब से simple और useful सलाह दे सकती हूं.\n\nआज क्या जानना चाहेंगी?",
  typing: "FlowAI सोच रहा है...",
  input_placeholder: "FlowAI Coach से पूछें...",
  ask_flowai: "FlowAI से पूछें",
};

export const hindiTextMap: Record<string, string> = {
  "Preferences": "पसंद की सेटिंग्स",
  "Display Units": "यूनिट सेटिंग्स",
  "Weight Unit": "वजन की यूनिट",
  "Preferred unit for weight logs": "वजन लॉग करने के लिए आपकी पसंदीदा यूनिट",
  "Height Unit": "हाइट की यूनिट",
  "Preferred unit for height measurements": "हाइट के लिए आपकी पसंदीदा यूनिट",
  "Language": "भाषा",
  "Currency": "करेंसी",
  "App interface language": "ऐप किस भाषा में दिखेगा",
  "English": "English",
  "Español": "Español",
  "हिन्दी": "हिन्दी",
  "Preferred Currency": "पसंदीदा करेंसी",
  "Currency for pricing details": "कीमत दिखाने के लिए करेंसी",
  "Daily Health Goals": "रोज के हेल्थ गोल",
  "Water Intake (ml)": "पानी कितना पीना है (ml)",
  "Daily Steps": "रोज के स्टेप्स",
  "Sleep Duration (hours)": "नींद का समय (घंटे)",
  "Saving...": "सेव हो रहा है...",
  "Save Preferences": "सेटिंग्स सेव करें",
  "Preferences Saved!": "सेटिंग्स सेव हो गईं!",
  "Account Settings": "अकाउंट सेटिंग्स",
  "Account & Security": "अकाउंट और सुरक्षा",
  "Payment Method": "पेमेंट तरीका",
  "Payment Methods": "पेमेंट तरीके",
  "Add Payment Method": "पेमेंट तरीका जोड़ें",
  "UPI Payment": "UPI पेमेंट",
  "Enter UPI ID": "UPI ID डालें",
  "Payment Summary": "पेमेंट summary",
  "UPI / QR Code": "UPI / QR कोड",
  "UPI Mobile / QR Pay": "UPI मोबाइल / QR पे",
  "Select UPI App to pay": "पेमेंट के लिए UPI ऐप चुनें",
  "Verify & Confirm Payment": "पेमेंट verify करके confirm करें",
  "Confirm Card Payment": "कार्ड पेमेंट confirm करें",
  "Scan this QR code with your chosen UPI application to transfer": "अपने UPI ऐप से यह QR स्कैन करके पेमेंट करें",
  "UPI Ref No. / UTR (12-Digits)": "UPI Ref No. / UTR (12 अंक)",
  "Having payment issues? Verify UTR": "पेमेंट में दिक्कत है? UTR verify करें",
  "Enter 12-digit UPI UTR / Ref No.": "12 अंकों का UPI UTR / Ref No. डालें",
  "Premium": "प्रीमियम",
  "Upgrade to Premium": "प्रीमियम लें",
  "Billing": "बिलिंग",
  "Cancel Subscription": "सब्सक्रिप्शन बंद करें",
  "Home": "होम",
  "Calendar": "कैलेंडर",
  "Log": "लॉग",
  "AI Coach": "AI कोच",
  "Account": "अकाउंट",
  "Good morning": "गुड मॉर्निंग",
  "Good afternoon": "गुड आफ्टरनून",
  "Good evening": "गुड इवनिंग",
  "How are you feeling?": "आज आप कैसा महसूस कर रही हैं?",
  "Today's Overview": "आज का ओवरव्यू",
  "Insights": "इनसाइट्स",
  "Phase Insight": "फेज इनसाइट",
  "Cycle Length": "साइकिल की लंबाई",
  "Period Length": "पीरियड की लंबाई",
  "Next Period": "अगला पीरियड",
  "AI Next Period": "AI वाला अगला पीरियड",
  "Water Today": "आज का पानी",
  "Log Symptoms": "लक्षण लॉग करें",
  "Track body & mood": "शरीर और मूड ट्रैक करें",
  "Track your cycle journey": "अपनी cycle journey ट्रैक करें",
  "Fertile Window": "फर्टाइल विंडो",
  "Edit Period Dates": "पीरियड की तारीख बदलें",
  "No log for this day yet": "इस दिन का कोई लॉग नहीं है",
  "Add log": "लॉग जोड़ें",
  "Normal": "नॉर्मल",
  "Prediction": "प्रेडिक्शन",
  "My Cycles": "मेरी cycles",
  "Health": "हेल्थ",
  "Health Report": "हेल्थ रिपोर्ट",
  "PCOS": "PCOS",
  "Tracker": "ट्रैकर",
  "Symptoms": "लक्षण",
  "Mood": "मूड",
  "Weight": "वजन",
  "Temperature": "टेम्परेचर",
  "Water": "पानी",
  "Steps": "स्टेप्स",
  "Sleep": "नींद",
  "Today": "आज",
  "This Week": "इस हफ्ते",
  "This Month": "इस महीने",
  "Save": "सेव करें",
  "Cancel": "रद्द करें",
  "Close": "बंद करें",
  "Done": "हो गया",
  "Continue": "आगे बढ़ें",
  "Back": "वापस",
  "Next": "आगे",
  "Skip": "स्किप करें",
  "Get Started": "शुरू करें",
  "Sign In": "साइन इन",
  "Sign Up": "साइन अप",
  "Log Out": "लॉग आउट",
  "Reminder": "रिमाइंडर",
  "Notification Preferences": "नोटिफिकेशन सेटिंग्स",
  "Mark all read": "सबको read करें",
  "No notifications": "कोई notification नहीं",
  "Personal Data": "पर्सनल डेटा",
  "Your Name": "आपका नाम",
  "Birthday": "जन्मदिन",
  "Last Period Date": "आखिरी पीरियड की तारीख",
  "Save Changes": "बदलाव सेव करें",
  "Changes Saved!": "बदलाव सेव हो गए!",
  "Ask FlowAI": "FlowAI से पूछें",
  "Ask FlowAI Coach...": "FlowAI Coach से पूछें...",
  "FlowAI is thinking...": "FlowAI सोच रहा है...",
  "FlowAI Circle": "FlowAI Circle",
  "Community": "कम्युनिटी",
  "Share, ask, and support women across health and daily life.": "हेल्थ और रोजमर्रा की जिंदगी पर महिलाओं से बात करें, पूछें और support दें.",
  "Keep it kind. Do not share emergency or private medical details. For urgent health issues, contact a doctor.": "बात प्यार से रखें. Emergency या private medical details शेयर न करें. Urgent health issue हो तो doctor से contact करें.",
  "All": "सभी",
  "Loading community": "कम्युनिटी लोड हो रही है",
  "Finding the newest conversations for you...": "आपके लिए नई conversations ढूंढ रहे हैं...",
  "Community setup needed": "कम्युनिटी setup चाहिए",
  "Start this circle": "यह circle शुरू करें",
  "No posts here yet. Share a question, story, or tiny win to begin the conversation.": "यहां अभी कोई post नहीं है. Conversation शुरू करने के लिए सवाल, story या छोटी जीत शेयर करें.",
  "New Post": "नई post",
  "Share real experiences, not private medical records. For emergencies, contact a doctor or local emergency service.": "अपना experience शेयर करें, private medical records नहीं. Emergency में doctor या local emergency service से contact करें.",
  "What do you want to ask or share?": "आप क्या पूछना या शेयर करना चाहती हैं?",
  "Post": "Post",
  "Write like you’re talking to another woman who gets it...": "ऐसे लिखें जैसे आप किसी समझने वाली महिला से बात कर रही हैं...",
  "Post to Community": "कम्युनिटी में post करें",
  "Conversation": "Conversation",
  "Replies": "Replies",
  "No replies yet. Be the first to support this conversation.": "अभी कोई reply नहीं है. सबसे पहले support दें.",
  "Write a kind reply...": "एक अच्छा reply लिखें...",
  "Report": "Report करें",
  "Reports help keep this women’s community respectful and safe.": "Reports इस women’s community को respectful और safe रखने में मदद करते हैं.",
  "Optional details": "Optional details",
  "Submit Report": "Report submit करें",
  "Retry": "फिर कोशिश करें",
  "Just now": "अभी",
  "Period Talk": "Period Talk",
  "PCOS Support": "PCOS Support",
  "Fertility & TTC": "Fertility & TTC",
  "Pregnancy": "Pregnancy",
  "Intimacy & Relationships": "Intimacy & Relationships",
  "Mood & Mental Wellness": "Mood & Mental Wellness",
  "Fitness & Nutrition": "Fitness & Nutrition",
  "Body Confidence": "Body Confidence",
  "General Women’s Circle": "General Women’s Circle",
};
