module.exports = {
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "accentgrey-e0e0e0": "var(--accentgrey-e0e0e0)",
        black: "var(--black)",
        "black-100": "var(--black-100)",
        "black-200": "var(--black-200)",
        "black-300": "var(--black-300)",
        "black-400": "var(--black-400)",
        "black-50": "var(--black-50)",
        "black-500": "var(--black-500)",
        "black-600": "var(--black-600)",
        "black-700": "var(--black-700)",
        "black-900": "var(--black-900)",
        "blue-100": "var(--blue-100)",
        "blue-600": "var(--blue-600)",
        "blue-700": "var(--blue-700)",
        "doctor-900": "var(--doctor-900)",
        "ioskey-background-highlight": "var(--ioskey-background-highlight)",
        "ioskey-label": "var(--ioskey-label)",
        "ioskeyboard-background": "var(--ioskeyboard-background)",
        "label-colorlightprimary": "var(--label-colorlightprimary)",
        "pink-100": "var(--pink-100)",
        "pink-200": "var(--pink-200)",
        "pink-300": "var(--pink-300)",
        "pink-400": "var(--pink-400)",
        "pink-50": "var(--pink-50)",
        "pink-500": "var(--pink-500)",
        "pink-600": "var(--pink-600)",
        "pink-700": "var(--pink-700)",
        "pink-800": "var(--pink-800)",
        "pink-900": "var(--pink-900)",
        "red-300": "var(--red-300)",
        "system-backgroundlightprimary": "var(--system-backgroundlightprimary)",
        "violet-100": "var(--violet-100)",
        "violet-200": "var(--violet-200)",
        "violet-300": "var(--violet-300)",
        "white-900": "var(--white-900)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "default-regular-callout": "var(--default-regular-callout-font-family)",
        "h1-bold-30": "var(--h1-bold-30-font-family)",
        "h1-regular-30": "var(--h1-regular-30-font-family)",
        "h2-bold-26": "var(--h2-bold-26-font-family)",
        "h2-medium-26": "var(--h2-medium-26-font-family)",
        "h3-bold-24": "var(--h3-bold-24-font-family)",
        "h4-bold-20": "var(--h4-bold-20-font-family)",
        "h4-medium-20": "var(--h4-medium-20-font-family)",
        "h4-semibold-20": "var(--h4-semibold-20-font-family)",
        "h5-bold-18": "var(--h5-bold-18-font-family)",
        "h5-medium-18": "var(--h5-medium-18-font-family)",
        "h5-reghular-18": "var(--h5-reghular-18-font-family)",
        "h5-semibold-18": "var(--h5-semibold-18-font-family)",
        "h6-bold-16": "var(--h6-bold-16-font-family)",
        "h6-medium-16": "var(--h6-medium-16-font-family)",
        "h6-regular-16": "var(--h6-regular-16-font-family)",
        "h6-semibold-16": "var(--h6-semibold-16-font-family)",
        "h7-medium-12": "var(--h7-medium-12-font-family)",
        "h7-regular-12": "var(--h7-regular-12-font-family)",
        "h7-semibold-12": "var(--h7-semibold-12-font-family)",
        "h8-medium-10": "var(--h8-medium-10-font-family)",
        "h8-semibold-10": "var(--h8-semibold-10-font-family)",
        "h9-medium-14": "var(--h9-medium-14-font-family)",
        "h9-regular-14": "var(--h9-regular-14-font-family)",
        "m-reguler-12": "var(--m-reguler-12-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: { "ios-background-blur": "var(--ios-background-blur)" },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
  darkMode: ["class"],
};
